### ISSUE TITLE
使用说明

### ISSUE THREAD

**Issue by mytea003** [abcz316/SKRoot-linuxKernelRoot#16]
为什么没有使用说明，不会用呀

**Comment by SeeFlowerX** [comment]
看这个帖子 https://bbs.kanxue.com/thread-276664.htm

**Comment by 71n9** [comment]
> 看这个帖子 https://bbs.kanxue.com/thread-276664.htm

看了只有简介，没有快速上手使用的步骤啊，希望弄一个快速使用的步骤说明

**Comment by dyboxoo** [comment]
都是拉本地buildapk和转exe。目前找地址很蛋疼。

**Comment by jindameias** [comment]
同，不知道怎么用

**Comment by dyboxoo** [comment]
ojbk。找地址很麻烦

**Comment by abcz316** [comment]
bilibili has been recorded by other friends and has been online for a long time. I suggest you visit and learn
