### ISSUE TITLE
安装部署su报错

### ISSUE THREAD

**Issue by Heresy-dd** [abcz316/SKRoot-linuxKernelRoot#17]
安装部署su报错
install su err:-52

**Comment by abcz316** [comment]
Please attach the detailed stack

**Comment by Heresy-dd** [comment]
![Screenshot_2023-03-31-19-45-04-12_2247b939c821775b783a915faf5f5b5e](https://user-images.githubusercontent.com/28682487/229111732-f0df39de-122e-4c84-9c49-8a88ac0ab391.jpg)
will you complete the ReadMe file?

**Comment by abcz316** [comment]
I have updated readme
