### ISSUE TITLE
How to use？

### ISSUE THREAD

**Issue by hiifong** [abcz316/SKRoot-linuxKernelRoot#19]

**Comment by abcz316** [comment]
Wait for me to record using the tutorial to upload to bilibili

**Comment by jindameias** [comment]
> Wait for me to record using the tutorial to upload to bilibili

大佬出了踢我一脚，感谢

**Comment by Jin1423** [comment]
> Wait for me to record using the tutorial to upload to bilibili

Make basic instructions on how to use to test project. Its long time past.

**Comment by abcz316** [comment]
> > Wait for me to record using the tutorial to upload to bilibili
> 
> Make basic instructions on how to use to test project. Its long time past.

bilibili has been recorded by other friends and has been online for a long time. I suggest you visit and learn

**Comment by abcz316** [comment]
> > Wait for me to record using the tutorial to upload to bilibili
> 
> 大佬出了踢我一脚，感谢

bilibili has been recorded by other friends and has been online for a long time. I suggest you visit and learn

**Comment by abcz316** [comment]
bilibili has been recorded by other friends and has been online for a long time. I suggest you visit and learn
