### ISSUE TITLE
添加的汇编代码的意义

### ISSUE THREAD

**Issue by 850352240** [abcz316/SKRoot-linuxKernelRoot#23]
请问能否大致解释下添加的汇编代码的意义？感觉明白为什么要添加这些代码，能更好的自己查错解决

**Comment by abcz316** [comment]
This assembly code is added for authentication and assertion, to bypass defense systems

**Comment by 850352240** [comment]
我是想知道反编译为高级程序语言，大致什么意思，比如 "B #" << do_execve_entry_hook_jump_back_addr - (hook_func_start_addr + 0x94) << endl;   这句跳转的位置，感觉很难理解

**Comment by abcz316** [comment]
This is to calculate the jump position of the assembly instruction, it is recommended to consult the aarch64 instruction manual

**Comment by zhuzhu-Top** [comment]
这段代码是保存寄存器
```
	       << "MOV X0, X0" << endl
		<< "STP X7, X8, [sp, #-16]!" << endl
		<< "STP X9, X10, [sp, #-16]!" << endl
		<< "STP X11, X12, [sp, #-16]!" << endl
```
这段是验证密钥
```
	       << "MOV X0, X0" 
		<< "STP X7, X8, [sp, #-16]!" 
		<< "STP X9, X10, [sp, #-16]!" 
		<< "STP X11, X12, [sp, #-16]!" 
		<< "MOV X7, 0xFFFFFFFFFFFFF001" 
		<< "CMP X1, X7" 
		<< "BCS #120" 
		<< "LDR X7, [X1]" 
		<< "CBZ X7, #112" 
		<< "ADR X8, #-84" 
		<< "MOV X9, #0" 
		<< "LDRB W10, [X7, X9]" 
		<< "CBZ W10, #96" 
		<< "LDRB W11, [X8, X9]" 
		<< "CBZ W11, #88" 
		<< "CMP W10, W11" 
		<< "B.NE #80" 
		<< "ADD X9, X9, 1" 
		<< "CMP X9, #" << str_root_key.length() 
		<< "BLT #-32" 
```
这下面是关键的:

SP_EL0拿到的就是task_struct 
我根据这里查到的   :  https://aijishu.com/a/1060000000366100
这段汇编给task_struct ->cred 的前40赋值为0, 40-80赋值为-1,再下面的代码同理,都是给相应的位置赋值而已
```
		<< "MRS X8, SP_EL0" 
		<< "LDR X10, [X8, #" << task_struct_offset_cred << "]" 
		<< "MOV X7, #4" 
		<< "MOV W9, WZR" 

		<< "STR W9, [X10, X7]" 
		<< "ADD X7, X7, 4" 
		<< "CMP X7, #40" 
		<< "BLT #-12" 


		<< "MOV W9, 0xFFFFFFFF" 
		<< "CMP X7, #80" 
		<< "BLT #-24" 
```

这段是恢复寄存器
```
                << "LDP X11, X12, [sp], #16" << endl
		<< "LDP X9, X10, [sp], #16" << endl
		<< "LDP X7, X8, [sp], #16" << endl
```
如有错误,欢迎指正

**Comment by 850352240** [comment]
> SP_EL0
感谢大佬

**Comment by 850352240** [comment]
> 这段代码是保存寄存器
> 
> ```
> 	       << "MOV X0, X0" << endl
> 		<< "STP X7, X8, [sp, #-16]!" << endl
> 		<< "STP X9, X10, [sp, #-16]!" << endl
> 		<< "STP X11, X12, [sp, #-16]!" << endl
> ```
> 
> 这段是验证密钥
> 
> ```
> 	       << "MOV X0, X0" 
> 		<< "STP X7, X8, [sp, #-16]!" 
> 		<< "STP X9, X10, [sp, #-16]!" 
> 		<< "STP X11, X12, [sp, #-16]!" 
> 		<< "MOV X7, 0xFFFFFFFFFFFFF001" 
> 		<< "CMP X1, X7" 
> 		<< "BCS #120" 
> 		<< "LDR X7, [X1]" 
> 		<< "CBZ X7, #112" 
> 		<< "ADR X8, #-84" 
> 		<< "MOV X9, #0" 
> 		<< "LDRB W10, [X7, X9]" 
> 		<< "CBZ W10, #96" 
> 		<< "LDRB W11, [X8, X9]" 
> 		<< "CBZ W11, #88" 
> 		<< "CMP W10, W11" 
> 		<< "B.NE #80" 
> 		<< "ADD X9, X9, 1" 
> 		<< "CMP X9, #" << str_root_key.length() 
> 		<< "BLT #-32" 
> ```
> 
> 这下面是关键的:
> 
> SP_EL0拿到的就是task_struct 我根据这里查到的 : https://aijishu.com/a/1060000000366100 这段汇编给task_struct ->cred 的前40赋值为0, 40-80赋值为-1,再下面的代码同理,都是给相应的位置赋值而已
> 
> ```
> 		<< "MRS X8, SP_EL0" 
> 		<< "LDR X10, [X8, #" << task_struct_offset_cred << "]" 
> 		<< "MOV X7, #4" 
> 		<< "MOV W9, WZR" 
> 
> 		<< "STR W9, [X10, X7]" 
> 		<< "ADD X7, X7, 4" 
> 		<< "CMP X7, #40" 
> 		<< "BLT #-12" 
> 
> 
> 		<< "MOV W9, 0xFFFFFFFF" 
> 		<< "CMP X7, #80" 
> 		<< "BLT #-24" 
> ```
> 
> 这段是恢复寄存器
> 
> ```
>                 << "LDP X11, X12, [sp], #16" << endl
> 		<< "LDP X9, X10, [sp], #16" << endl
> 		<< "LDP X7, X8, [sp], #16" << endl
> ```
> 
> 如有错误,欢迎指正

感谢大佬

**Comment by 850352240** [comment]
@zhuzhu-Top 不过大佬，还有个问题，最后一句跳转，<< "B #" << do_execve_entry_hook_jump_back_addr - (hook_func_start_addr + 0x94) << endl;   这最终是跳转到哪里？这样跳转不是最终地址会和hook_func_start_addr直接有关吗？为什么要和hook_func_start_addr有关？

**Comment by iamfaith** [comment]
感谢🙏
