### ISSUE TITLE
TracerPid text->0x00000000017E71F0 [ERROR] text offset empty. 

### ISSUE THREAD

**Issue by wutaijieing** [abcz316/SKRoot-linuxKernelRoot#24]
proc_pid_status一直无法正确找到偏移，或者教下如何用ida来查找，
内核文件：
[Image](https://drive.google.com/file/d/1_7iyBiccGfholZ-4G6NmNVZgPmzffZCf/view?usp=sharing)

还有就是如果直接拖入kernel.img或者解包后的kernel.img-kernel，均无法通过find找到任何数据

**Comment by abcz316** [comment]
Thank you for providing the kernel. I have analyzed this kernel and fixed the issue with the searcher. Please pull the code again

**Comment by wutaijieing** [comment]
> Thank you for providing the kernel. I have analyzed this kernel and fixed the issue with the searcher. Please pull the code again

关于直接拖入kernel.img或者解包后的kernel.img-kernel，均无法通过find找到任何数据，可以帮看下是什么原因吗？再次感谢
内核是华为4.9.111版本：

[kernel](https://drive.google.com/drive/folders/1VZIzZ-erNYy1TKhqZtcd119jrxdNCYWJ?usp=sharing)

**Comment by wutaijieing** [comment]
关于直接拖入kernel.img或者解包后的kernel.img-kernel，均无法通过find找到任何数据，可以帮看下是什么原因吗？再次感谢
内核是华为4.9.111版本：

[kernel](https://drive.google.com/drive/folders/1VZIzZ-erNYy1TKhqZtcd119jrxdNCYWJ?usp=sharing)

生成过程：
cat Image | gzip -n -f -9 > Image.gz

mv Image.gz kernel

./mkbootimg --kernel kernel --base 0x0 --cmdline "loglevel=4 initcall_debug=n page_tracker=on unmovable_isolate1=2:192M,3:224M,4:256M printktimer=0xfff0a000,0x534,0x538 androidboot.selinux=enforcing buildvariant=user" --tags_offset 0x07A00000 --kernel_offset 0x00080000 --ramdisk_offset 0x07c00000 --header_version 1 --os_version 9 --os_patch_level 2019-03-01 --output kernel4.9.111.img

**Comment by abcz316** [comment]
I have checked your Huawei kernel, there is no problem, the tool runs normally

**Comment by df13954** [comment]
我用了最新版本，也遇到了这个错误。https://wwsk.lanzouy.com/itJuv0shy68j，boot的地址

**Comment by wutaijieing** [comment]
> 
使用do_execve 001AEBBC   avc:003A65C8 cred 0x840  seccomp 0x8F8
这几个入口点

内核文件
[Image](https://drive.google.com/file/d/1_7iyBiccGfholZ-4G6NmNVZgPmzffZCf/view?usp=sharing)

pm点击获取root权限的时候软件闪退 ，dmesg获取到下面几个日志：
[ 1463.174682] [pid:981,cpu1,wificond][W][vap:0]{wal_cfg80211_get_station::rssi -23.} [F:1205][L:4427]
[ 1463.328186] [pid:396,cpu0,kworker/u16:6]wifi sleep cmd send ,wakelock cnt 1
[ 1463.421325] [pid:108,cpu1,kworker/u16:1]wifi wakeup cmd send,wakelock cnt 2
[ 1463.577606] [pid:6165,cpu1,kworker/u16:2]wifi sleep cmd send ,wakelock cnt 1
[ 1463.620727] [pid:396,cpu3,kworker/u16:6][hisi_coul_core]coul_ntc_temperature_compensation: current = 0, temp_without_compensation = 330, temp_with_compensation = 330
[ 1463.620758] [pid:396,cpu3,kworker/u16:6][hisi_coul_core]stably temp!,old_temp =330,cnt =1, temp = 330
[ 1463.625579] [pid:108,cpu1,kworker/u16:1]wifi wakeup cmd send,wakelock cnt 2
[ 1463.716461] [pid:6167,cpu0,rmissionmanager]UID root escalation!
[ 1463.716491] [pid:6188,cpu3,Profile Saver]UID root escalation!
[ 1463.716888] [pid:6188,cpu3,Profile Saver]UID root escalation!
[ 1463.716888] [pid:6188,cpu3,Profile Saver]UID root escalation!
[ 1463.812652] [pid:6198,cpu5,mali-utility-wo]mali gpufreq: kctx 0000000000000000 being destroyed
[ 1463.883361] [pid:108,cpu1,kworker/u16:1]wifi sleep cmd send ,wakelock cnt 1
[ 1463.932189] [pid:108,cpu0,kworker/u16:1]wifi wakeup cmd send,wakelock cnt 2
[ 1464.092712] [2023:04:15 02:44:37][pid:6165,cpu1,kworker/u16:2]wifi sleep cmd send ,wakelock cnt 1
[ 1464.137359] [pid:108,cpu2,kworker/u16:1]wifi wakeup cmd send,wakelock cnt 2
[ 1464.291687] [pid:108,cpu3,kworker/u16:1]wifi sleep cmd send ,wakelock cnt 1
[ 1464.387207] [pid:241,cpu0,kworker/0:1H]sp805-wdt e8a06000.watchdog0: watchdog kick now 32K 47979182 rqclock 1450718691067 ret 1
[ 1464.547485] [pid:6165,cpu2,kworker/u16:2]wifi wakeup cmd send,wakelock cnt 2
[ 1464.704040] [pid:396,cpu2,kworker/u16:6]wifi sleep cmd send ,wakelock cnt 1
[ 1464.751708] [pid:396,cpu1,kworker/u16:6]wifi wakeup cmd send,wakelock cnt 2
[ 1464.912139] [pid:6165,cpu1,kworker/u16:2]wifi sleep cmd send ,wakelock cnt 1
[ 1464.956390] [pid:108,cpu1,kworker/u16:1]wifi wakeup cmd send,wakelock cnt 2
[ 1465.111541] [2023:04:15 02:44:38][pid:396,cpu1,kworker/u16:6]wifi sleep cmd send ,wakelock cnt 1
[ 1465.111938] [pid:396,cpu1,kworker/u16:6]wifi wakeup cmd send,wakelock cnt 2
[ 1465.216186] [pid:396,cpu3,kworker/u16:6]wifi sleep cmd send ,wakelock cnt 1
[ 1465.375915] [pid:396,cpu1,kworker/u16:6][hisi_get_charger_type]type: sdp
[ 1465.376220] [pid:396,cpu1,kworker/u16:6][I/usb_short_circuit_protect] tusb adc value [0]=32

使用的内核源代码：
https://github.com/wutaijieing/Code_Opensource_kirin710/tree/main/kernel


大佬，求救，是入口点问题还是内核限制了？
