### ISSUE TITLE
一个很旧的内核cred偏移值无法确定

### ISSUE THREAD

**Issue by zl521368789** [abcz316/SKRoot-linuxKernelRoot#25]
你好，我的设备是小米mix2，内核为linux4.4.153-perf+，aarch64架构，解压获得的boot，ida加载起始地址FFFFFF8008080000
[boot.zip](https://github.com/abcz316/SKRoot-linuxKernelRoot/files/11183746/boot.zip)
通过ida搜索函数do_execve得到入口地址FFFFFF80081C83F4（减去起始地址为0x1483f4）
![do_execve](https://user-images.githubusercontent.com/42074803/230734197-fb7f1fbd-58ab-4f2e-89f5-5b06e586bfc4.png)
通过ida搜索函数avc_denied得到入口地址FFFFFF80082E20D0（减去起始地址为0x2620d0）
![do_execve](https://user-images.githubusercontent.com/42074803/230734567-65e3c7a3-e5b0-46ec-8299-5550c510b41e.png)
通过搜索task_struct并没有得到我想要的cred偏移值，通过拖拽内核的方法并未得到任何结果，通过搜索proc_pid_status函数从伪代码中仍旧无法得到Uid的值，可以得到seccomp的值（0x858）
![Uid](https://user-images.githubusercontent.com/42074803/230734901-5854fb83-2eff-46fe-bb98-30da5bbd23ca.png)
![seccomp](https://user-images.githubusercontent.com/42074803/230734908-8ef5043c-18b9-4046-b851-c105059bd638.png)
通过一些合理的猜测cred的值进行测试，手机不能正常开机。

**Comment by zl521368789** [comment]
![avc_denied](https://user-images.githubusercontent.com/42074803/230735330-0b419a68-a1fb-4e37-81f5-dbd80c769d5b.png)
avc_denied地址图放错了（第二张图），现在改正

**Comment by abcz316** [comment]
Thank you for your feedback, find_proc_pid_status The issue of no output result for status has been fixed by me. Please pull the code again. The kernel file you provided is very easy to analyze. By using the proc_pid_status function, you can directly determine that Uid comes from a variable with a value of 7B8. By using the+8 offset value, you can obtain the correct cred offset value, which is 7C0

**Comment by zl521368789** [comment]
感谢您的深夜回复，重新进行了测试并flash boot，手机再次不开机，刷回未经更改的boot正常开机
![boot](https://user-images.githubusercontent.com/42074803/230739332-ba788212-3d7c-40f3-9daa-ecb9bfe769eb.png)
不知道哪里的原因，这个问题已经困扰了我10天

**Comment by zl521368789** [comment]
如果问题得到解决，我愿意为您录制一个关于这种旧版内核地址定位的视频

**Comment by abcz316** [comment]
There's no video required, and I'm advocating that you don't need the source code to manipulate the kernel. Please check the way your kernel files are repackaged

**Comment by zl521368789** [comment]
我并没有使用源代码操作内核，我直接解压boot.img得到的boot(或许比较老的内核可以这样尝试，这种方法也许是错误的)。
*通过拖拽内核(boot.img)至三个find_xxx.exe,均未给出结果。
1.通过拖拽内核解压文件(boot)至find_do_execve,似乎并未给出正确的do_execve的地址，经过ida伪代码提示给出的代码在do_execveat_common_isra_40这个函数中。同时通过您最新更新的patch代码我找到上次的错误，地址%8并不等于0，目前并未找到正确的入口地址。
2.通过拖拽内核解压文件(boot)至find_cred_has_capability，在这个函数中找到avc_has_perm_noaudit，进入函数才能找到avc_denied函数。（直接寻找是没有的）
3.通过拖拽内核解压文件(boot)至find_proc_pid_status，成功找到cred和seccomp的值。
另外我使用patch写入的时候似乎需要在patch的目录下存在aarch64-linux-android-as.exe才能正常工作，也许是编译的不对？
[boot.zip](https://github.com/abcz316/SKRoot-linuxKernelRoot/files/11185066/boot.zip)
解压可获得boot.img,解压boot.img可获得boot。

**Comment by abcz316** [comment]
Now, you can trust the tool to give you the correct address. I have removed the %8 limit, please pull the code again

**Comment by WenXin0405** [comment]
> 如果问题得到解决，我愿意为您录制一个关于这种旧版内核地址定位的视频

加我q 8501390 同低版本

**Comment by jimmy0435** [comment]
@zl521368789 我也遇到需要aarch64-linux-android-as.exe，請問您解決這問題了嗎?

**Comment by jxwdsb** [comment]
能来个视频吗，我k20 pro ，三个地址都没有
