### ISSUE TITLE
怎么编译 patch_kernel_root.cpp 是我用g++ 版本不对吗？  使用命令g++  patch_kernel_root.cpp -o patch_root.exe

### ISSUE THREAD

**Issue by wangyuxiang147** [abcz316/SKRoot-linuxKernelRoot#27]
PS C:\Users\Ad\Downloads\SKRoot-linuxKernelRoot-master\patch_kernel_root>g++  --version                              
g++.exe (Rev10, Built by MSYS2 project) 12.2.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO 
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# -------------------------------------------------------------------------------------------------

PS C:\Users\Ad\Downloads\SKRoot-linuxKernelRoot-master\patch_kernel_root> g++  patch_kernel_root.cpp -o patch_root.exe        
In file included from patch_kernel_root.cpp:9:
ArmAsmHelper.h: In function 'std::string AsmToBytes(const std::string&)':
ArmAsmHelper.h:59:43: warning: ignoring return value of 'bool std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::empty() const [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]', declared with attribute 'nodiscard' [-Wunused-result]
   59 |                                 word.empty();
      |                                 ~~~~~~~~~~^~
In file included from C:/msys64/mingw64/include/c++/12.2.0/string:53,
                 from C:/msys64/mingw64/include/c++/12.2.0/bits/locale_classes.h:40,
                 from C:/msys64/mingw64/include/c++/12.2.0/bits/ios_base.h:41,
                 from C:/msys64/mingw64/include/c++/12.2.0/ios:42,
                 from C:/msys64/mingw64/include/c++/12.2.0/ostream:38,
                 from C:/msys64/mingw64/include/c++/12.2.0/iostream:39,
                 from patch_kernel_root.cpp:4:
C:/msys64/mingw64/include/c++/12.2.0/bits/basic_string.h:1183:7: note: declared here
 1183 |       empty() const _GLIBCXX_NOEXCEPT
      |       ^~~~~
patch_kernel_root.cpp: In function 'size_t path_do_execve(const char*, const std::string&, size_t, size_t, size_t, size_t, std::vector<patch_bytes_data>&)':
patch_kernel_root.cpp:69:63: error: expected primary-expression before 'const'
   69 |         string str_show_root_key_mem_byte = bytesToHexString((const byte*)str_root_key.c_str(), str_root_key.length());
      |                                                               ^~~~~
patch_kernel_root.cpp:69:63: error: expected ')' before 'const'
   69 |         string str_show_root_key_mem_byte = bytesToHexString((const byte*)str_root_key.c_str(), str_root_key.length());
      |                                                              ~^~~~~
      |                                                               )
patch_kernel_root.cpp:124:51: error: expected primary-expression before 'const'
  124 |         string strHookOrigCmd = bytesToHexString((const byte*)hookOrigCmd, sizeof(hookOrigCmd));
      |                                                   ^~~~~
patch_kernel_root.cpp:124:51: error: expected ')' before 'const'
  124 |         string strHookOrigCmd = bytesToHexString((const byte*)hookOrigCmd, sizeof(hookOrigCmd));
      |                                                  ~^~~~~
      |                                                   )
patch_kernel_root.cpp: In function 'size_t path_avc_denied(const char*, size_t, size_t, size_t, std::vector<patch_bytes_data>&)':
patch_kernel_root.cpp:175:51: error: expected primary-expression before 'const'
  175 |         string strHookOrigCmd = bytesToHexString((const byte*)hookOrigCmd, sizeof(hookOrigCmd));
      |                                                   ^~~~~
patch_kernel_root.cpp:175:51: error: expected ')' before 'const'
  175 |         string strHookOrigCmd = bytesToHexString((const byte*)hookOrigCmd, sizeof(hookOrigCmd));
      |                                                  ~^~~~~
      |                                                   )
patch_kernel_root.cpp: In function 'int main(int, char**)':
patch_kernel_root.cpp:305:25: error: 'shared_ptr' was not declared in this scope
  305 |                         shared_ptr<char> spData(new (std::nothrow) char[item.str_bytes.length() / 2], std::default_delete<char[]>());
      |                         ^~~~~~~~~~
patch_kernel_root.cpp:10:1: note: 'std::shared_ptr' is defined in header '<memory>'; did you forget to '#include <memory>'?
    9 | #include "ArmAsmHelper.h"
  +++ |+#include <memory>
   10 |
patch_kernel_root.cpp:305:36: error: expected primary-expression before 'char'
  305 |                         shared_ptr<char> spData(new (std::nothrow) char[item.str_bytes.length() / 2], std::default_delete<char[]>());
      |                                    ^~~~
patch_kernel_root.cpp:306:78: error: 'spData' was not declared in this scope
  306 |                         hex2byte((uint8_t*)item.str_bytes.c_str(), (uint8_t*)spData.get());

**Comment by wangyuxiang147** [comment]
已经解决了 谢谢

**Comment by wangyuxiang147** [comment]
> 我也遇到相同的问题，请问你是怎么解决的？

c++ 版本问题  c++17 新增了std::byte

**Comment by a857795** [comment]
要用17的版本吧？
