### ISSUE TITLE
Nexus 6p 根据readme path 开机正常，但是无法安装部署su

### ISSUE THREAD

**Issue by wangyuxiang147** [abcz316/SKRoot-linuxKernelRoot#28]
你好，我的设备是Nexus 6（android8.1），根据readme文档path内核后能正常开机，但是好像并没有root成功，调试源代码查看错误信息
create_su_hide_folder error:/data/local/tmp/su_40ab264ef2659a3da13690e41d41a8274c9cc1086dfd016989de0561fc61a4d47bec2d5094d9125e98db3c4785e61c54ae22628934aa30478ec301759b33ba3b5b9bd21fbb2ca823bd13699dc0294ab5c2/

![f57faabff70614d1dfed684d20ea8d0a](https://user-images.githubusercontent.com/37867145/231077564-09d5db8a-1174-4d9b-a3f5-7e76fb520938.jpg)
上传两个内核文件
里面文件分别是
kernel_core_rebuild 是经过patch_kernel_root 后的内核文件， 
kernel_core_bak 是原内核文件
[kernel_core_rebuild.zip](https://github.com/abcz316/SKRoot-linuxKernelRoot/files/11197405/kernel_core_rebuild.zip)
patch_kernel_root执行步骤，不知道是不是这几个函数入口和偏移没有找对（我是结合 [一个很旧的内核cred偏移值无法确定](https://github.com/abcz316/SKRoot-linuxKernelRoot/issues/25)  里的图片找的这几个入口和偏移）
请输入do_execve函数的入口位置：
0x291dbc
请输入avc_denied函数的入口位置：
0x37bc34
请输入task_struct结构体里cred的十六进制偏移值（从proc_pid_status里能看到）：
0x4e8
请输入task_struct结构体里seccomp的十六进制偏移值（从proc_pid_status里能看到）：
0x940
是否需要自动随机生成ROOT密匙（1需要；2不需要）：
1

**Comment by abcz316** [comment]
Your kernel version is 3. X, which is quite old, and your do_execve address is also incorrect. The correct address is 002918C8

**Comment by wangyuxiang147** [comment]
> 我总觉得我直接进行解压的方式不太对，因为没办法还原为boot.img。我很好奇您的解包方式，如何从boot.img到kernel_core?
你试试这个工具
[BootImgTool](https://github.com/Forgo7ten/BootImgTool)

**Comment by wangyuxiang147** [comment]
> 我总觉得我直接进行解压的方式不太对，因为没办法还原为boot.img。我很好奇您的解包方式，如何从boot.img到kernel_core?

目前我的也是还原为boot.img，也是无线重启，我过两天换台小米8的手机再试试

**Comment by wangyuxiang147** [comment]
> Your kernel version is 3. X, which is quite old, and your do_execve address is also incorrect. The correct address is 002918C8

谢谢，可能是手机内核太老了，我过两天换台小米8试试
