### ISSUE TITLE
大佬，点获取root权限时闪退

### ISSUE THREAD

**Issue by wutaijieing** [abcz316/SKRoot-linuxKernelRoot#30]
使用do_execve 001AEBBC avc:003A65C8 cred 0x840 seccomp 0x8F8
这几个入口点

内核文件
[Image](https://drive.google.com/file/d/1_7iyBiccGfholZ-4G6NmNVZgPmzffZCf/view?usp=sharing)

pm点击获取root权限的时候软件闪退 ，dmesg获取到下面几个日志：
[ 1463.174682] [pid:981,cpu1,wificond][W][vap:0]{wal_cfg80211_get_station::rssi -23.} [F:1205][L:4427]
[ 1463.328186] [pid:396,cpu0,kworker/u16:6]wifi sleep cmd send ,wakelock cnt 1
[ 1463.421325] [pid:108,cpu1,kworker/u16:1]wifi wakeup cmd send,wakelock cnt 2
[ 1463.577606] [pid:6165,cpu1,kworker/u16:2]wifi sleep cmd send ,wakelock cnt 1
[ 1463.620727] [pid:396,cpu3,kworker/u16:6][hisi_coul_core]coul_ntc_temperature_compensation: current = 0, temp_without_compensation = 330, temp_with_compensation = 330
[ 1463.620758] [pid:396,cpu3,kworker/u16:6][hisi_coul_core]stably temp!,old_temp =330,cnt =1, temp = 330
[ 1463.625579] [pid:108,cpu1,kworker/u16:1]wifi wakeup cmd send,wakelock cnt 2
[ 1463.716461] [pid:6167,cpu0,rmissionmanager]UID root escalation!
[ 1463.716491] [pid:6188,cpu3,Profile Saver]UID root escalation!
[ 1463.716888] [pid:6188,cpu3,Profile Saver]UID root escalation!
[ 1463.716888] [pid:6188,cpu3,Profile Saver]UID root escalation!
[ 1463.812652] [pid:6198,cpu5,mali-utility-wo]mali gpufreq: kctx 0000000000000000 being destroyed
[ 1463.883361] [pid:108,cpu1,kworker/u16:1]wifi sleep cmd send ,wakelock cnt 1
[ 1463.932189] [pid:108,cpu0,kworker/u16:1]wifi wakeup cmd send,wakelock cnt 2
[ 1464.092712] [2023:04:15 02:44:37][pid:6165,cpu1,kworker/u16:2]wifi sleep cmd send ,wakelock cnt 1
[ 1464.137359] [pid:108,cpu2,kworker/u16:1]wifi wakeup cmd send,wakelock cnt 2
[ 1464.291687] [pid:108,cpu3,kworker/u16:1]wifi sleep cmd send ,wakelock cnt 1
[ 1464.387207] [pid:241,cpu0,kworker/0:1H]sp805-wdt e8a06000.watchdog0: watchdog kick now 32K 47979182 rqclock 1450718691067 ret 1
[ 1464.547485] [pid:6165,cpu2,kworker/u16:2]wifi wakeup cmd send,wakelock cnt 2
[ 1464.704040] [pid:396,cpu2,kworker/u16:6]wifi sleep cmd send ,wakelock cnt 1
[ 1464.751708] [pid:396,cpu1,kworker/u16:6]wifi wakeup cmd send,wakelock cnt 2
[ 1464.912139] [pid:6165,cpu1,kworker/u16:2]wifi sleep cmd send ,wakelock cnt 1
[ 1464.956390] [pid:108,cpu1,kworker/u16:1]wifi wakeup cmd send,wakelock cnt 2
[ 1465.111541] [2023:04:15 02:44:38][pid:396,cpu1,kworker/u16:6]wifi sleep cmd send ,wakelock cnt 1
[ 1465.111938] [pid:396,cpu1,kworker/u16:6]wifi wakeup cmd send,wakelock cnt 2
[ 1465.216186] [pid:396,cpu3,kworker/u16:6]wifi sleep cmd send ,wakelock cnt 1
[ 1465.375915] [pid:396,cpu1,kworker/u16:6][hisi_get_charger_type]type: sdp
[ 1465.376220] [pid:396,cpu1,kworker/u16:6][I/usb_short_circuit_protect] tusb adc value [0]=32

使用的内核源代码：
https://github.com/wutaijieing/Code_Opensource_kirin710/tree/main/kernel

大佬，求救，是入口点问题还是内核限制了？

**Comment by abcz316** [comment]
Your log has shown that obtaining root succeeded, the flash back should be the problem of permission manager. I adjusted the code logic of permission manager, please pull the code of permission manager and try again

**Comment by wutaijieing** [comment]
> Your log has shown that obtaining root succeeded, and the crash should be the problem of permission manager. I adjusted the code logic of permission manager, please pull the code of permission manager and try again

不行，点击测试root权限现在没有日志了，点击执行root命令提示err: -113，执行原生内核命令err:-64002，安装部署提示err：-512

dmesg日志也均有显示[pid:4704,cpu4,rmissionmanager]UID root escalation!

**Comment by Debug-boy** [comment]
const struct cred __rcu *real_cred; /* objective and real subjective task
	const struct cred __rcu *cred;	/* effective (overridable) subjective task
你找的cred 偏移为:0x840 是不是找错了,n感觉你找的应该是real_cred cred=real_cred+8

**Comment by Debug-boy** [comment]
我自己也没有成功,大致问题和你的差不多，部署root返回-503

**Comment by wutaijieing** [comment]
> ```
> const struct cred __rcu *real_cred; /* objective and real subjective task
> const struct cred __rcu *cred;	/* effective (overridable) subjective task
> ```
> 
> 你找的cred 偏移为:0x840 是不是找错了,n感觉你找的应该是real_cred cred=real_cred+8

都试了，不行，感觉是华为的锅

**Comment by abcz316** [comment]
You can compile testRoot to test it. It may be a flash crash at the Android level that does not affect Linux kernel provisioning

**Comment by Gunkkk** [comment]
> > ```
> > const struct cred __rcu *real_cred; /* objective and real subjective task
> > const struct cred __rcu *cred;	/* effective (overridable) subjective task
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 你找的cred 偏移为:0x840 是不是找错了,n感觉你找的应该是real_cred cred=real_cred+8
> 
> 都试了，不行，感觉是华为的锅

华为一般带rkp

**Comment by abcz316** [comment]
Thank you for your feedback. It has been fixed
