### ISSUE TITLE
向service manager发送请求依然被selinux拦截

### ISSUE THREAD

**Issue by 850352240** [abcz316/SKRoot-linuxKernelRoot#33]
04-22 07:54:28.411   467   467 E SELinux : avc:  denied  { find } for service=window pid=2848 uid=0 scontext=u:r:untrusted_app:s0:c102,c256,c512,c768 tcontext=u:object_r:window_service:s0 tclass=service_manager permissive=0
请问大佬，为何这个操作依然被selinux拦截？

**Comment by abcz316** [comment]
Check that the patch address is correct, and check the capability set and seccomp, and that there is no process fork operation
