### ISSUE TITLE
三星 android 8.0 kernel 3.18 修改后卡开机logo无限重启

### ISSUE THREAD

**Issue by WenXin0405** [abcz316/SKRoot-linuxKernelRoot#34]
测试hook 挑战过去什么不操作在跳转回来是可以开机的
patch_kernel_root 后就无法开机了,
单独hook path_do_execve 或者 path_avc_denied 都无法开机
是因为我内核版本太低了吗?

do_execve 141E58
avc_denied 293750
cred 668
seccomp AD8
cred 是 get_task_cred 里面 0x660 + 8
函数入口是直接打印了内核符号表看到的

**Comment by WenXin0405** [comment]
入口地址是我读了内核符号表获取到的

**Comment by WenXin0405** [comment]
do_execve:  141E58

**Comment by WenXin0405** [comment]
do_execve

**Comment by WenXin0405** [comment]
do_execve   141E58
avc_denied  293750
cred  668
seccomp  AD8
cred 是 get_task_cred 里面  0x660 + 8
函数入口是直接打印了内核符号表看到的

**Comment by abcz316** [comment]
You got the wrong do_execve, you got to use the do_execve_comm

**Comment by WenXin0405** [comment]
我在patch_kernel_root看到cred的读取方式是这样
  << "MRS X7, SP_EL0" << endl
  << "LDR X7, [X7, #" << task_struct_offset_cred << "]" << endl
  如果这样读取cred 只hook avc_denied 也是无法开机的
我在do_execve中看到这样一段汇编 里面也有一个0x668
    .text:0000000000141EA0 00 41 38 D5                   MRS             X0, #0, c4, c1, #0
    .text:0000000000141EA4 00 08 40 F9                   LDR             X0, [X0,#0x10]
    .text:0000000000141EA8 01 14 40 B9                   LDR             W1, [X0,#0x14]
    .text:0000000000141EAC 01 01 60 36                   TBZ             W1, #0xC, loc_141ECC
    .text:0000000000141EAC
    .text:0000000000141EB0 01 34 43 F9                   LDR             X1, [X0,#0x668]
不知道他俩是相同的么?   我给avc_denied 改成这样 是可以开机的
    << "MRS X7, SP_EL0" << endl
    << "LDR X7, [X7, #16]" << endl
    << "LDR X7, [X7, #" << task_struct_offset_cred << "]" << endl

**Comment by abcz316** [comment]
I don't know what you're talking about. I think your revision is totally illogical

**Comment by WenXin0405** [comment]
cred 0x668
seccomp 0xAD8
0x141E58 do_execve_common.isra.28
0x293750 avc_denied.isra.2

[image and kallsyms](https://drive.google.com/drive/folders/1uZxBsOOu_q2_7GR_rV8BM-6BGbJkQCYE)

无限卡开机logo重启,是因为我的偏移或者入口点错误吗?  检查了下 之前用的141E58 就是 do_execve_common

**Comment by WenXin0405** [comment]
![1111](https://user-images.githubusercontent.com/81508716/233838266-cd1c3f11-b1b3-45d1-8a98-ddcaeee4f3fc.png)
![1112](https://user-images.githubusercontent.com/81508716/233838271-6cced547-69e5-4553-80ef-1f183bb6aed5.png)
请教,  0x660 不是read_cred的偏移吗? 我是用0x660+8作为cred的话,无法开机

**Comment by WenXin0405** [comment]
![116](https://user-images.githubusercontent.com/81508716/233839641-59f0a028-0305-4f6a-b31d-39f2d84a8e59.png)
![117](https://user-images.githubusercontent.com/81508716/233839644-b021417d-abae-4d25-9f10-39624306e44b.png)
在其他函数看  cred的偏移也是0x660  但是我用0x660+8 就卡logo无法开机  有可能是因为内核版本太低,hook的代码不对吗?

**Comment by zl521368789** [comment]
我尝试了nexus 6p，3.x内核同样也是卡logo不开机。通过查询你的kernel，你找的四个值并没有错误。也许是这种方法并不适用于3.x内核。

**Comment by WenXin0405** [comment]
> 我尝试了nexus 6p，3.x内核同样也是卡logo不开机。通过查询你的kernel，你找的四个值并没有错误。也许是这种方法并不适用于3.x内核。

我发现了问题
<< "MRS X7, SP_EL0" << endl
<< "LDR X7, [X7, #" << task_struct_offset_cred << "]" << endl
<< "CBZ X7, #84" << endl
<< "MOV X8, #4" << endl
<< "MOV W9, WZR" << endl
<< "LDR W10, [X7, X8]" << endl


SP_EL0 -> task_struct - > *cred(+668) + 4  只要读(<< "LDR W10, [X7, X8]" << endl )就会卡开机,

**Comment by yuguigang** [comment]
我尝试了pixel 3.18内核，同样卡在logo不开机。同样方法查询的4个值。可能如上所述，不适用3.x内核。
