### ISSUE TITLE
请教,三星 cred 写入后 死机自动重启, 是触发了RKP保护吗?

### ISSUE THREAD

**Issue by WenXin0405** [abcz316/SKRoot-linuxKernelRoot#37]
<< "LDR X10, [X8, #" << task_struct_offset_cred << "]" << endl
<< "MOV X7, #4" << endl
<< "MOV W9, WZR" << endl
<< "STR W9, [X10, X7]" << endl
您好,请教下, cred + i * 4 写0,就会导致死机自动重启
我测试目前可以正常开机,rootkey校验正常, 点击测试root就会死机重启
我搜索到RKP好像对cred有保护,请教下是因为写cred触发了保护机制吗?

**Comment by WenXin0405** [comment]
实测低版本三星低版本内核写cred会触发RKP保护,测试使用第三方内核修改成功,官方内核不行

**Comment by yuguigang** [comment]
> 实测低版本三星低版本内核写cred会触发RKP保护,测试使用第三方内核修改成功,官方内核不行

求教，我pixel 3.18 kernel也是无限重启。请问你刷哪个三方内核能修改成功，我想试试。能不能把你得到的4个参数分享下，我老觉得我没找对。
