### ISSUE TITLE
cred lookup failed, I need help

### ISSUE THREAD

**Issue by jxwdsb** [abcz316/SKRoot-linuxKernelRoot#38]
不知道是不是IDA的问题

[img.kernel](https://drive.google.com/file/d/1RO0MpmWBwSPFVlNahEDKuP4Y5kon--oU/view?usp=share_link)

我把img kernel 拖拽进去只能识别为binary file 文件
Processor type我手动选择成 ARM Little-endian

IDA View-A窗口显示的是.ROM 不是.TEXT
按g跳转到地址，然后按c，但是此时按F5没反应

我双击每个sub函数跳转过去再按F5有反应，能找到avc_denied，但是找不到cred 和 seccomp
do_execve
2372C0
avc_denied
43ECC8

我加个英语方便下一个英语使用的查问题

I don't know if it's an IDA problem

[img.kernel](https://drive.google.com/file/d/1RO0MpmWBwSPFVlNahEDKuP4Y5kon--oU/view?usp=share_link)

I dragged the img kernel into it and it can only be recognized as a binary file file
Processor type I manually choose to be ARM Little-endian

IDA View-A window shows .ROM not .TEXT
Press g to jump to the address, and then press c, but there is no response to pressing F5 at this time

I double-click each sub function to jump to it and then press F5 to respond. I can find avc_denied, but I can’t find cred and seccomp
do_execve
2372C0
avc_denied
43ECC8

**Comment by abcz316** [comment]
Hello, thank you very much for watching the tutorial, but there are some questions about the use of IDA tools. I suggest you read the book and study this project after mastering the use of IDA

**Comment by jxwdsb** [comment]
> Hello, thank you very much for watching the tutorial, but there are some questions about the use of IDA tools. I suggest you read the book and study this project after mastering the use of IDA

就是我的IDA打开文件没有Portable executable for ARM64 ,只有 Binary file 选项，导致我打开显示的是.ROM 而不是 .TEXT,导致无法跳转

That is, my IDA opened the file without Portable executable for ARM64, only the Binary file option, which caused me to open and display .ROM instead of .TEXT, which made it impossible to jump

**Comment by jxwdsb** [comment]
> Hello, thank you very much for watching the tutorial, but there are some questions about the use of IDA tools. I suggest you read the book and study this project after mastering the use of IDA

我已经找好了 刷入了新boot ,但是 终端输入下面的命令 设备就会卡住，然后重启
I have already found it and flashed the new boot, but the device will be stuck when the terminal enters the following command, and then restarts

IIaF7vBhC9ZZQkp09gf9nDA2tLSa2ROMbQqhlgFTn1e4xA5K/su

[booty.img-kernel](https://drive.google.com/file/d/1RO0MpmWBwSPFVlNahEDKuP4Y5kon--oU/view?usp=share_link)

do_execve 2372C0
avc_denied 43ECC8
cred 808
Seccomp 888

**Comment by jxwdsb** [comment]
谢谢，我成功了!

**Comment by yuguigang** [comment]
你好，请教cred 808是怎么来的？我查找貌似只找到值为7D0。
