### ISSUE TITLE
红米6pro 3.18内核  patch后无法开机

### ISSUE THREAD

**Issue by 850352240** [abcz316/SKRoot-linuxKernelRoot#39]
patch后无法开机。
然后我在未patch的kernel的ffffffc000080300添加了一个汇编函数，仅仅一个指令RET，不使用这个函数，可以正常启动内核。我把do_execve的BL nullsub替换为BL 我创建的函数，便依然无法开机。请问为什么无法调用自己添加的函数？希望大佬能给些思路。

**Comment by abcz316** [comment]
Thank you for your feedback. It has been fixed.
