### ISSUE TITLE
About so injection, safe_inject_process64_so_wrapper

### ISSUE THREAD

**Issue by jxwdsb** [abcz316/SKRoot-linuxKernelRoot#40]
这个函数有例子吗,第一个rootkey,第二个目标进程pid,第三个待注入的so路径，第四个是待注入so里面的函数吗?
safe_inject_process64_so_wrapper函数 执行不成功阿
safe_inject_process_run_exit_wrapper 这个函数我可以执行

Is there an example of this function, the first rootkey, the second target process pid, the third so path to be injected, and the fourth is the function to be injected into so?
The safe_inject_process64_so_wrapper function failed to execute
safe_inject_process_run_exit_wrapper I can execute this function

**Comment by abcz316** [comment]
Sorry, none. Because of the SELinux context of your target process, it does not have permission to load your so file

**Comment by jxwdsb** [comment]
> Sorry, none. Because of the SELinux context of your target process, it does not have permission to load your so file

这个函数是不是有问题，so文件已经放到目标进程文件夹中，/data/user/0/PackageName/，777的权限,和文件权限无关，它应该可以读取的 ，safe_inject_process64_so_wrapper 函数好像有问题，没有按照期望工作

Is there a problem with this function? The so file has been placed in the target process folder, /data/user/0/PackageName/, the permission of 777 has nothing to do with the file permission. It should be readable. There seems to be a problem with the safe_inject_process64_so_wrapper function. not working as expected

**Comment by abcz316** [comment]
In your knowledge, is the file permission only 777 this attribute? It is recommended that you carefully relearn LINUX system programming or read the LINUX kernel source code
