### ISSUE TITLE
小米11安卓12的内核，参考了b站视频，能帮忙看看这个是什么错误么

### ISSUE THREAD

**Issue by Whitebird0** [abcz316/SKRoot-linuxKernelRoot#42]
<img width="1090" alt="image" src="https://user-images.githubusercontent.com/75669133/236816676-61fd87dc-7c48-4fac-ad57-e5c7dc69364f.png">

**Comment by Iamxiaoq** [comment]
我也踩过这个坑，我当时是直接使用的msvc cl编译，编译出来的exe怀疑是size_t是64位的，导致两个偏移相减得到一个很大的负数，超过了B指令能编码的offset。后面参考别人fork这个项目的github action解决了，https://github.com/DataEraserC/SKRoot-linuxKernelRoot/blob/master/.github/workflows/SKRootKernelRoot_Windows.yml

**Comment by abcz316** [comment]
Any kernel of mi11 models has been confirmed to run skroot normally, you do not have to question, if you have other problems please debug the source code
