### ISSUE TITLE
redmi k20 pro 设备，最拖拽进去找不到do_execve ,附boot.img 

### ISSUE THREAD

**Issue by jxwdsb** [abcz316/SKRoot-linuxKernelRoot#43]
k20 pro 设备，拖拽进去找不到do_execve,附带boot.img
[boot.img](https://drive.google.com/file/d/1e8tJTC_BPZZrRHDfD5zaQoZDh4jg_tMq/view?usp=share_link)

![image](https://github.com/abcz316/SKRoot-linuxKernelRoot/assets/22835510/0e00fbdc-303a-4c17-964c-0a0bad0bc75b)

**Comment by abcz316** [comment]
Any kernel of k20 and k20 pro models has been confirmed to run skroot normally, you do not have to question, if you have other problems please debug the source code
