### ISSUE TITLE
大佬好，可以看下我这个内核为什么找不到do_execve吗

### ISSUE THREAD

**Issue by a869072989** [abcz316/SKRoot-linuxKernelRoot#48]
大佬好，附件在:
 123pan:https://www.123pan.com/s/w51tVv-QGe6d.html
 google:https://drive.google.com/file/d/15X6V9_N0m592f-A-elEEH1gqCZvUpjG4/view?usp=sharing

固件是小米5s capricorn_images_9.8.29_20190829.0000.00_8.0_cn线刷包提取的
附件包含boot.img 以及用Android-Image-Tools-windows从boot.img提取的boot.img-zImage 。boot是从boot.img-zImage 解压后的内核文件！d把boot文件拖到find_do_execve.exe会提示:
![2222](https://github.com/abcz316/SKRoot-linuxKernelRoot/assets/17998169/80c4d335-c903-4d49-a1f9-0852c5c7473c)
盼望大佬有空能给看下

**Comment by K-Found** [comment]
0x002b88d4 t do_execve_common.isra.30
0x002b8e48 T do_execve
0x0040f5b4 t avc_denied


0x001bf5a0 T revert_creds
0x00233e58 T prctl_get_seccomp

**Comment by abcz316** [comment]
Thank you for your feedback. It has been fixed.

**Comment by lmhdrive** [comment]
> 大佬好，附件在: 123pan:https://www.123pan.com/s/w51tVv-QGe6d.html google:https://drive.google.com/file/d/15X6V9_N0m592f-A-elEEH1gqCZvUpjG4/view?usp=sharing
> 
> 固件是小米5s capricorn_images_9.8.29_20190829.0000.00_8.0_cn线刷包提取的 附件包含boot.img 以及用Android-Image-Tools-windows从boot.img提取的boot.img-zImage 。boot是从boot.img-zImage 解压后的内核文件！d把boot文件拖到find_do_execve.exe会提示: ![2222](https://private-user-images.githubusercontent.com/17998169/242933871-80c4d335-c903-4d49-a1f9-0852c5c7473c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzODAwNjIsIm5iZiI6MTczMDM3OTc2MiwicGF0aCI6Ii8xNzk5ODE2OS8yNDI5MzM4NzEtODBjNGQzMzUtYzkwMy00ZDQ5LWExZjktMDg1MmM1Yzc0NzNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMxVDEzMDI0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmN2M0M2JjZDU2ZThjMGY4ZDIyNTEwNzYwOTU4NDZiYjU3ZGM4YzkwNGU2ZTA5ZDdlMDhlZGE0NDU0NzI2MDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.EGIsl4fun4BTfpG4uSPsshc5xyTAdHjw3NuinpaqQcc) 盼望大佬有空能给看下

兄弟你的问题应该解决了吧？我试了一下现在没问题了。就是有个问题不明白，请问生成的a.out文件是做啥用的？
