### ISSUE TITLE
大佬您好

### ISSUE THREAD

**Issue by Demon7899** [abcz316/SKRoot-linuxKernelRoot#52]
我的手机是小米6x，从官方的9.0刷机包提取的boot，并且函数定位我是导出的手机里的符号文件，使用ida脚本批量设置函数，然后把每个需要的偏移地址拿到，并且补丁后我也用ida看了，感觉hook也在正确的位置上，但是打包刷入后，使用管理器检测root权限时手机就重启了，请问我应该排查哪里的问题？

**Comment by Demon7899** [comment]
能否上传一个patch好的其他kernel我对照一下？

**Comment by abcz316** [comment]
Thank you for your feedback. It has been fixed.
