### ISSUE TITLE
skroot 无法执行wm等 系统命令

### ISSUE THREAD

**Issue by jxwdsb** [abcz316/SKRoot-linuxKernelRoot#56]
无法执行wm等 系统命令

比如 wm size的命令
直接/system/bin/wm size
也不是想要的结果

**Comment by abcz316** [comment]
To use the interactive commands of this Android framework, please manually inject the correct Android context.

**Comment by qiurigao** [comment]
> 要使用此 Android 框架的交互式命令，请手动注入正确的 Android 上下文。

可否举个例子
