### ISSUE TITLE
如果能用github action自动编译exe和apk就更好了

### ISSUE THREAD

**Issue by longhuan1999** [abcz316/SKRoot-linuxKernelRoot#58]

**Comment by longhuan1999** [comment]
没想到我手机的内核是压缩过的，从boot.img中提取出来后还得解压一下才能patch。不仅如此，内核文件后面还追加了dtb，直接解压会被丢弃，得用工具提取出来，等解压后的内核patch并重新压缩好了得再追加到文件后面才能打包成boot.img，否则是开不了机的。就这样整整摸鱼折腾了两天。

**Comment by longhuan1999** [comment]
怎么打包patch_kernel_root.exe也摸索出来了，现在只剩下打包PermissionManager.apk还没摸索出来
我已经不记得修改过多少次action ci了，就是卡在':app:buildCMakeRelWithDebInfo'报错：
```
/usr/local/lib/android/sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/filesystem:1871: undefined reference to `std::__ndk1::__fs::filesystem::__remove_all(std::__ndk1::__fs::filesystem::path const&, std::__ndk1::error_code*)'
  clang++: error: linker command failed with exit code 1
```

**Comment by longhuan1999** [comment]
又摸鱼了两天，终于搞定 PermissionManager 的打包，原来是 Gradle 7.2 默认安装的 NDK 版本太低不能完全地支持 filesystem
<picture><img src="https://github.com/abcz316/SKRoot-linuxKernelRoot/assets/43313501/c8709d3f-df18-4a33-9270-02b8e21e487d" width="50%" style="visibility:visible;max-width:100%;"></picture>

**Comment by longhuan1999** [comment]
没想到还有有效期限制，虽然水平不够花了些时间，但好像还是找到改掉了，就是不知道改的对不对。整个过程下来感觉挺像闯关打BOSS的

**Comment by abcz316** [comment]
最后您成功了吗？

**Comment by longhuan1999** [comment]
是的，不过钛备份有警告运行不太正常
<figure class="half">
<img src="https://github.com/abcz316/SKRoot-linuxKernelRoot/assets/43313501/2ff3fdaa-3272-4f52-a242-ccb831791049" width="40%">
<img src="https://github.com/abcz316/SKRoot-linuxKernelRoot/assets/43313501/b2ecb43b-51cc-4fe8-918d-86d40e6e9c7e" width="40%">
</figure>

**Comment by abcz316** [comment]
谢谢你的支持，下个月的月初我将会开放寄生目标APP功能的源代码，以彻底解决管理APP无法隐藏的问题。

**Comment by longhuan1999** [comment]
不客气，同时感谢你的开发和开源。另外，SKRoot的隐藏Bootloader锁模块是不公开了吗？我找不着。

**Comment by abcz316** [comment]
Thank you for your feedback. It has been fixed.
