### ISSUE TITLE
android13-5.15 won't boot, how fix this

### ISSUE THREAD

**Issue by jxwdsb** [abcz316/SKRoot-linuxKernelRoot#59]
android13-5.15 won't boot,  how fix this

**Comment by jxwdsb** [comment]
> The reason is that the 300 address in the header is referenced, you can manually modify the address here, I will submit the automated modification code later

Thanks for your help, I tried, but still can't boot

**Comment by abcz316** [comment]
Where did you change to? Please make sure that the location you modified is clean

**Comment by jxwdsb** [comment]
> Where did you change to? Please make sure that the location you modified is clean

It may be caused by my modification mistake, I will try again by replacing other devices

**Comment by folie123** [comment]
hello, i have the same problem, how can i solve it
