### ISSUE TITLE
鸿蒙2.0.0.263(C00E263R2P3)无法注入init执行命令

### ISSUE THREAD

**Issue by eveing** [abcz316/SKRoot-linuxKernelRoot#60]
.../SKRoot/testRoot # cat /proc/1/maps | grep libc
7fa6200000-7fa6600000 rw-p 00000000 00:00 0                              [anon:libc_malloc]
7fa6600000-7fa6601000 ---p 00000000 00:00 0                              [anon:libc_malloc]
7fa6601000-7fa6800000 rw-p 00000000 00:00 0                              [anon:libc_malloc]
7fa8200000-7fa8201000 ---p 00000000 00:00 0                              [anon:libc_malloc]
7fa8201000-7fa8600000 rw-p 00000000 00:00 0                              [anon:libc_malloc]
找不到libc.so，不能setenforce就是被SELinux约束的root

**Comment by abcz316** [comment]
Thank you for your feedback. It has been fixed.
