### ISSUE TITLE
想请教一下如何测试如此多的实验设备？

### ISSUE THREAD

**Issue by MirageTurtle** [abcz316/SKRoot-linuxKernelRoot#80]
您好！

我想请教一下大佬是如何测试如此多的实验设备？还是说只是根据对应的kernel去在同一个物理机上刷机实验呢？

因为似乎项目没开Discussion，我就直接提Issue了。

**Comment by abcz316** [comment]
It is very simple to first determine that skroot is universal in principle, and then skroot is sent to various mobile phone enthusiasts, and the test results are out. What kind of equipment do you have now that can also be tested, after all, it is open source

**Comment by MirageTurtle** [comment]
Thank you very much for your replay!

Actually, I'm trying to do some security research, which maybe need multi-platform test. So I want to know how you do and if that way is cheap.

Thank you again!
